# Generated by Django 3.0.6 on 2020-05-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20200516_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='done',
        ),
    ]
